name: lint-and-test
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          pip install -r requirements-server.txt
      - name: Black formatting
        run: |
          black --check .
      - name: Pylint check
        run: |
          pylint *.py cogs database services tests graphapi
      - name: Pyright check
        run: |
          pyright .
      - name: Unit tests
        run: |
          python3 -m unittest
